# Generated by Django 4.2.7 on 2023-11-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todos', '0003_alter_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=9),
        ),
    ]
